#ifndef __UM_H
#define __UM_H

#ifdef __linux__
#include <linux/ioctl.h>
#include <linux/kdev_t.h>

#define UM_DEVICE_NAME		"ksm"
#define UM_DEVICE_PATH		"/dev/" UM_DEVICE_NAME

#define KSM_DEVICE_MAGIC	'K'
#define KSM_IOCTL_SANDBOX	_IOR(KSM_DEVICE_MAGIC, 0, int)
#define KSM_IOCTL_SUBVERT	_IOR(KSM_DEVICE_MAGIC, 1, int)
#define KSM_IOCTL_UNSUBVERT	_IOW(KSM_DEVICE_MAGIC, 2, int)
#else
#define UM_DEVICE_NAME		L"ksm"
#define UM_DEVICE_PATH		L"\\\\.\\" UM_DEVICE_NAME

#define KSM_DEVICE_NAME		L"\\Device\\" UM_DEVICE_NAME
#define KSM_DOS_NAME		L"\\DosDevices\\" UM_DEVICE_NAME

#define KSM_DEVICE_MAGIC	0x00008008
#define KSM_IOCTL_SANDBOX	(ULONG)CTL_CODE(KSM_DEVICE_MAGIC, 0x800, \
					METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define KSM_IOCTL_SUBVERT	(ULONG)CTL_CODE(KSM_DEVICE_MAGIC, 0x801, \
					METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define KSM_IOCTL_UNSUBVERT	(ULONG)CTL_CODE(KSM_DEVICE_MAGIC, 0x802, \
					METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#endif
#endif
